name: Github_Actions_Study

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 📙Checkout
        uses: actions/checkout@v4
      
      - name: print
        run: ls -a
        
      - name: 📄Create-vite-env 
        run: |  ##한줄일때는 <<EOL > ~ EOL대신에 echo "VITE_PORTONE_STOREID=${{ secrets.VITE_PORTONE_STOREID }}" > ./.env
          chmod 777 -R front
          cat <<EOL > front/.env  
          VITE_PORTONE_STOREID=${{ secrets.VITE_PORTONE_STOREID }}
          VITE_PORTONE_API_KEY=${{ secrets.VITE_PORTONE_API_KEY }}
          EOL
          cat front/.env
          
      - name: 📄Create-application-secret
        run: |
          chmod 777 -R back
          cat <<EOL > back/src/main/resources/application-secret.yml
          spring:
            config:
              activate:
                on-profile: secret

            datasource:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://${{ secrets.EC2_PUBLIC_IP }}:3306/${{ secrets.DATABASE_NAME }}
              username: ${{ secrets.DATABASE_USERNAME }}
              password: ${{ secrets.DATABASE_PASSWORD }}

            mail:
              host: smtp.gmail.com
              port: 587
              username: ${{ secrets.EMAIL_USERNAME }}
              password: ${{ secrets.EMAIL_PASSWORD }}
              properties:
                mail:
                  smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                      enable: true

            security:
              oauth2:
                client:
                  registration:
                    google:
                      client-id: ${{ secrets.OAUTH2_ID_GOOGLE }}
                      client-secret: ${{ secrets.OAUTH2_SECRET_GOOGLE }}
                    naver:
                      client-id: eFbja8kX2crbBVBob6cH ${{ secrets.OAUTH2_ID_NAVER }}
                      client-secret: HoboXn5qY2  ${{ secrets.OAUTH2_SECRET_NAVER }}

          jwt: 
            secret: ${{ secrets.JWT_SECRET }}
          EOL
          cat back/src/main/resources/application-secret.yml
          
      - name: print-directory
        run: |
          ls -a front
          ls -a back/src/main/resources

      - name: 🌕DockerHub-LOGIN
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏭Build-And-Push-React-App
        run: |
          cd front
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kiosk-react-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/kiosk-react-app:latest
      - name: 🏭Build-And-Push-Spring-App
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kiosk-spring-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/kiosk-spring-app:latest

  deploy:
    needs: build-push ##해당 잡이 완료되야 작동
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/kiosk-react-app:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/kiosk-spring-app:latest
            cd /home/ubuntu/project
            sudo docker-compose -f project-compose.yml down
            sudo docker-compose -f project-compose.yml up -d
          

      
    
