name: Github_Actions_Study

on:
  push:
    branches: ["main"]

jobs:
  job-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: print
        run: ls -a
        
      - name: create-vire-env
        run: |
          chmod 777 -R front
          cd front
          echo "VITE_PORTONE_STOREID=${{ secrets.VITE_PORTONE_STOREID }}" > ./. env
          cat .env
